#include "eos_editor_plugin.h"

#include <godot_cpp/classes/editor_export_platform.hpp>
#include <godot_cpp/classes/file_access.hpp>
#include <godot_cpp/core/error_macros.hpp>
#include <godot_cpp/variant/utility_functions.hpp>

namespace godot::eos::editor {

void EOSEditorPlugin::_bind_methods() {}

void EOSEditorPlugin::_generate_env_template() {
    // 在项目根生成 .env 模板，提示用户填写 EOS ClientId 等凭据。
    const char *template_content =
            "# --- Generated by GD-EOS Editor Plugin. ---\n"
            "# GD-EOS only use \"CLIENT_ID\" for android export plugin.\n"
            "# RECOMMEND: exclude this file from version control.\n"
            "# RECOMMEND: exclude this file from exporting.\n"
            "#\n"
            "# \"CLIENT_ID\" in \"res://.env\" or system environment variable \"EOS_CLIENT_ID\"/\"CLIENT_ID\" is used for GD-EOS's android exporting.\n"
            "# Please get from your Epic Dev Portal(https://dev.epicgames.com/portal/) and fill these values.\n"
            "\n"
            "PRODUCT_NAME=MyGame\n"
            "PRODUCT_VERSION=1.0.0\n"
            "PRODUCT_ID=your_product_id\n"
            "SANDBOX_ID=your_sandbox_id\n"
            "DEPLOYMENT_ID=your_deployment_id\n"
            "CLIENT_ID=your_client_id\n"
            "CLIENT_SECRET=your_client_secret\n"
            "ENCRYPTION_KEY=your_encryption_key\n";

    Ref<FileAccess> f = FileAccess::open("res://.env", FileAccess::WRITE);
    if (f.is_valid()) {
        f->store_string(template_content);
        UtilityFunctions::print("GD-EOS: \"res://.env\" generated.");
    } else {
        ERR_PRINT(vformat("GD-EOS: generate \"res://.env\" failed: %s", FileAccess::get_open_error()));
    }
}

static constexpr const char *TOOL_MENU_ITEM_NAME = "GD-EOS: generate \"res://.env\"";

void EOSEditorPlugin::_notification(int p_what) {
    switch (p_what) {
        case NOTIFICATION_ENTER_TREE: {
            // 注册安卓自动配置导出插件。
            android_export_plugin.instantiate();
            add_export_plugin(android_export_plugin);

            // 添加工具菜单项：生成 .env 模板。
            Callable cb = callable_mp(this, &EOSEditorPlugin::_generate_env_template);
            add_tool_menu_item(TOOL_MENU_ITEM_NAME, cb);
        } break;
        case NOTIFICATION_EXIT_TREE: {
            remove_tool_menu_item(TOOL_MENU_ITEM_NAME);

            if (android_export_plugin.is_valid()) {
                remove_export_plugin(android_export_plugin);
                android_export_plugin.unref();
            }
        } break;
        default:
            break;
    }
}
} //namespace godot::eos::editor
